//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FelicitySecurity.Applications.Config.FelicitySecurityServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FelicitySecurityServiceReference.IFelicitySecurityDataService")]
    public interface IFelicitySecurityDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelicitySecurityDataService/GetData", ReplyAction="http://tempuri.org/IFelicitySecurityDataService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelicitySecurityDataService/GetData", ReplyAction="http://tempuri.org/IFelicitySecurityDataService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelicitySecurityDataService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IFelicitySecurityDataService/GetDataUsingDataContractResponse")]
        FelicitySecurity.Services.CompositeType GetDataUsingDataContract(FelicitySecurity.Services.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelicitySecurityDataService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IFelicitySecurityDataService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<FelicitySecurity.Services.CompositeType> GetDataUsingDataContractAsync(FelicitySecurity.Services.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelicitySecurityDataService/DoWork", ReplyAction="http://tempuri.org/IFelicitySecurityDataService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelicitySecurityDataService/DoWork", ReplyAction="http://tempuri.org/IFelicitySecurityDataService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFelicitySecurityDataServiceChannel : FelicitySecurity.Applications.Config.FelicitySecurityServiceReference.IFelicitySecurityDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FelicitySecurityDataServiceClient : System.ServiceModel.ClientBase<FelicitySecurity.Applications.Config.FelicitySecurityServiceReference.IFelicitySecurityDataService>, FelicitySecurity.Applications.Config.FelicitySecurityServiceReference.IFelicitySecurityDataService {
        
        public FelicitySecurityDataServiceClient() {
        }
        
        public FelicitySecurityDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FelicitySecurityDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FelicitySecurityDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FelicitySecurityDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public FelicitySecurity.Services.CompositeType GetDataUsingDataContract(FelicitySecurity.Services.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<FelicitySecurity.Services.CompositeType> GetDataUsingDataContractAsync(FelicitySecurity.Services.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
    }
}
