//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FelicitySecurity.Core.FelicitySecurityDataServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Administrators_dto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Administrators_dto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AdminIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdminNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdminEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdminPinCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int AdminID {
            get {
                return this.AdminIDField;
            }
            set {
                if ((this.AdminIDField.Equals(value) != true)) {
                    this.AdminIDField = value;
                    this.RaisePropertyChanged("AdminID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AdminName {
            get {
                return this.AdminNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminNameField, value) != true)) {
                    this.AdminNameField = value;
                    this.RaisePropertyChanged("AdminName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AdminEmail {
            get {
                return this.AdminEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminEmailField, value) != true)) {
                    this.AdminEmailField = value;
                    this.RaisePropertyChanged("AdminEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AdminPinCode {
            get {
                return this.AdminPinCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminPinCodeField, value) != true)) {
                    this.AdminPinCodeField = value;
                    this.RaisePropertyChanged("AdminPinCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Members_dto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Members_dto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MemIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemFirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemLastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemPhonenumberField;
        
        private System.Nullable<System.DateTime> MemDOBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemPostcodeField;
        
        private System.Nullable<bool> MemStatusField;
        
        private System.Nullable<System.DateTime> MemRegDateField;
        
        private System.Nullable<bool> IsStaffField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] MemFacialImageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MemID {
            get {
                return this.MemIDField;
            }
            set {
                if ((this.MemIDField.Equals(value) != true)) {
                    this.MemIDField = value;
                    this.RaisePropertyChanged("MemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MemFirstname {
            get {
                return this.MemFirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.MemFirstnameField, value) != true)) {
                    this.MemFirstnameField = value;
                    this.RaisePropertyChanged("MemFirstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MemLastname {
            get {
                return this.MemLastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.MemLastnameField, value) != true)) {
                    this.MemLastnameField = value;
                    this.RaisePropertyChanged("MemLastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MemPhonenumber {
            get {
                return this.MemPhonenumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MemPhonenumberField, value) != true)) {
                    this.MemPhonenumberField = value;
                    this.RaisePropertyChanged("MemPhonenumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<System.DateTime> MemDOB {
            get {
                return this.MemDOBField;
            }
            set {
                if ((this.MemDOBField.Equals(value) != true)) {
                    this.MemDOBField = value;
                    this.RaisePropertyChanged("MemDOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string MemPostcode {
            get {
                return this.MemPostcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MemPostcodeField, value) != true)) {
                    this.MemPostcodeField = value;
                    this.RaisePropertyChanged("MemPostcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<bool> MemStatus {
            get {
                return this.MemStatusField;
            }
            set {
                if ((this.MemStatusField.Equals(value) != true)) {
                    this.MemStatusField = value;
                    this.RaisePropertyChanged("MemStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<System.DateTime> MemRegDate {
            get {
                return this.MemRegDateField;
            }
            set {
                if ((this.MemRegDateField.Equals(value) != true)) {
                    this.MemRegDateField = value;
                    this.RaisePropertyChanged("MemRegDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<bool> IsStaff {
            get {
                return this.IsStaffField;
            }
            set {
                if ((this.IsStaffField.Equals(value) != true)) {
                    this.IsStaffField = value;
                    this.RaisePropertyChanged("IsStaff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public byte[] MemFacialImage {
            get {
                return this.MemFacialImageField;
            }
            set {
                if ((object.ReferenceEquals(this.MemFacialImageField, value) != true)) {
                    this.MemFacialImageField = value;
                    this.RaisePropertyChanged("MemFacialImage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Staff_dto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Staff_dto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int StaffIDField;
        
        private System.Nullable<bool> IsStaffField;
        
        private System.Nullable<int> BadgeNoField;
        
        private int MemIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FelicitySecurity.Core.FelicitySecurityDataServiceReference.Members_dto[] StaffMembersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int StaffID {
            get {
                return this.StaffIDField;
            }
            set {
                if ((this.StaffIDField.Equals(value) != true)) {
                    this.StaffIDField = value;
                    this.RaisePropertyChanged("StaffID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Nullable<bool> IsStaff {
            get {
                return this.IsStaffField;
            }
            set {
                if ((this.IsStaffField.Equals(value) != true)) {
                    this.IsStaffField = value;
                    this.RaisePropertyChanged("IsStaff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<int> BadgeNo {
            get {
                return this.BadgeNoField;
            }
            set {
                if ((this.BadgeNoField.Equals(value) != true)) {
                    this.BadgeNoField = value;
                    this.RaisePropertyChanged("BadgeNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int MemID {
            get {
                return this.MemIDField;
            }
            set {
                if ((this.MemIDField.Equals(value) != true)) {
                    this.MemIDField = value;
                    this.RaisePropertyChanged("MemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public FelicitySecurity.Core.FelicitySecurityDataServiceReference.Members_dto[] StaffMembers {
            get {
                return this.StaffMembersField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffMembersField, value) != true)) {
                    this.StaffMembersField = value;
                    this.RaisePropertyChanged("StaffMembers");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FelicitySecurityDataServiceReference.FelicitySecurityDataServiceSoap")]
    public interface FelicitySecurityDataServiceSoap {
        
        // CODEGEN: Generating message contract since element name item from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddAdministrator", ReplyAction="*")]
        FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddAdministratorResponse AddAdministrator(FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddAdministratorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddAdministrator", ReplyAction="*")]
        System.Threading.Tasks.Task<FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddAdministratorResponse> AddAdministratorAsync(FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddAdministratorRequest request);
        
        // CODEGEN: Generating message contract since element name FindAllAdministratorsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindAllAdministrators", ReplyAction="*")]
        FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllAdministratorsResponse FindAllAdministrators(FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllAdministratorsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindAllAdministrators", ReplyAction="*")]
        System.Threading.Tasks.Task<FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllAdministratorsResponse> FindAllAdministratorsAsync(FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllAdministratorsRequest request);
        
        // CODEGEN: Generating message contract since element name item from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMember", ReplyAction="*")]
        FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddMemberResponse AddMember(FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddMemberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMember", ReplyAction="*")]
        System.Threading.Tasks.Task<FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddMemberResponse> AddMemberAsync(FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddMemberRequest request);
        
        // CODEGEN: Generating message contract since element name FindAllMembersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindAllMembers", ReplyAction="*")]
        FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllMembersResponse FindAllMembers(FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllMembersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindAllMembers", ReplyAction="*")]
        System.Threading.Tasks.Task<FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllMembersResponse> FindAllMembersAsync(FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllMembersRequest request);
        
        // CODEGEN: Generating message contract since element name item from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddStaff", ReplyAction="*")]
        FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddStaffResponse AddStaff(FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddStaffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddStaff", ReplyAction="*")]
        System.Threading.Tasks.Task<FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddStaffResponse> AddStaffAsync(FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddStaffRequest request);
        
        // CODEGEN: Generating message contract since element name FindAllStaffResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindAllStaff", ReplyAction="*")]
        FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllStaffResponse FindAllStaff(FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllStaffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindAllStaff", ReplyAction="*")]
        System.Threading.Tasks.Task<FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllStaffResponse> FindAllStaffAsync(FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllStaffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveAdministrator", ReplyAction="*")]
        void RemoveAdministrator(int administratorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveAdministrator", ReplyAction="*")]
        System.Threading.Tasks.Task RemoveAdministratorAsync(int administratorId);
        
        // CODEGEN: Generating message contract since element name item from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateAdministrator", ReplyAction="*")]
        FelicitySecurity.Core.FelicitySecurityDataServiceReference.UpdateAdministratorResponse UpdateAdministrator(FelicitySecurity.Core.FelicitySecurityDataServiceReference.UpdateAdministratorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateAdministrator", ReplyAction="*")]
        System.Threading.Tasks.Task<FelicitySecurity.Core.FelicitySecurityDataServiceReference.UpdateAdministratorResponse> UpdateAdministratorAsync(FelicitySecurity.Core.FelicitySecurityDataServiceReference.UpdateAdministratorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAdministratorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddAdministrator", Namespace="http://tempuri.org/", Order=0)]
        public FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddAdministratorRequestBody Body;
        
        public AddAdministratorRequest() {
        }
        
        public AddAdministratorRequest(FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddAdministratorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddAdministratorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FelicitySecurity.Core.FelicitySecurityDataServiceReference.Administrators_dto item;
        
        public AddAdministratorRequestBody() {
        }
        
        public AddAdministratorRequestBody(FelicitySecurity.Core.FelicitySecurityDataServiceReference.Administrators_dto item) {
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAdministratorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddAdministratorResponse", Namespace="http://tempuri.org/", Order=0)]
        public FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddAdministratorResponseBody Body;
        
        public AddAdministratorResponse() {
        }
        
        public AddAdministratorResponse(FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddAdministratorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddAdministratorResponseBody {
        
        public AddAdministratorResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindAllAdministratorsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindAllAdministrators", Namespace="http://tempuri.org/", Order=0)]
        public FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllAdministratorsRequestBody Body;
        
        public FindAllAdministratorsRequest() {
        }
        
        public FindAllAdministratorsRequest(FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllAdministratorsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class FindAllAdministratorsRequestBody {
        
        public FindAllAdministratorsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindAllAdministratorsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindAllAdministratorsResponse", Namespace="http://tempuri.org/", Order=0)]
        public FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllAdministratorsResponseBody Body;
        
        public FindAllAdministratorsResponse() {
        }
        
        public FindAllAdministratorsResponse(FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllAdministratorsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindAllAdministratorsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FelicitySecurity.Core.FelicitySecurityDataServiceReference.Administrators_dto[] FindAllAdministratorsResult;
        
        public FindAllAdministratorsResponseBody() {
        }
        
        public FindAllAdministratorsResponseBody(FelicitySecurity.Core.FelicitySecurityDataServiceReference.Administrators_dto[] FindAllAdministratorsResult) {
            this.FindAllAdministratorsResult = FindAllAdministratorsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMemberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMember", Namespace="http://tempuri.org/", Order=0)]
        public FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddMemberRequestBody Body;
        
        public AddMemberRequest() {
        }
        
        public AddMemberRequest(FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddMemberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddMemberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FelicitySecurity.Core.FelicitySecurityDataServiceReference.Members_dto item;
        
        public AddMemberRequestBody() {
        }
        
        public AddMemberRequestBody(FelicitySecurity.Core.FelicitySecurityDataServiceReference.Members_dto item) {
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMemberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMemberResponse", Namespace="http://tempuri.org/", Order=0)]
        public FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddMemberResponseBody Body;
        
        public AddMemberResponse() {
        }
        
        public AddMemberResponse(FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddMemberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddMemberResponseBody {
        
        public AddMemberResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindAllMembersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindAllMembers", Namespace="http://tempuri.org/", Order=0)]
        public FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllMembersRequestBody Body;
        
        public FindAllMembersRequest() {
        }
        
        public FindAllMembersRequest(FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllMembersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class FindAllMembersRequestBody {
        
        public FindAllMembersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindAllMembersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindAllMembersResponse", Namespace="http://tempuri.org/", Order=0)]
        public FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllMembersResponseBody Body;
        
        public FindAllMembersResponse() {
        }
        
        public FindAllMembersResponse(FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllMembersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindAllMembersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FelicitySecurity.Core.FelicitySecurityDataServiceReference.Members_dto[] FindAllMembersResult;
        
        public FindAllMembersResponseBody() {
        }
        
        public FindAllMembersResponseBody(FelicitySecurity.Core.FelicitySecurityDataServiceReference.Members_dto[] FindAllMembersResult) {
            this.FindAllMembersResult = FindAllMembersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddStaffRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddStaff", Namespace="http://tempuri.org/", Order=0)]
        public FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddStaffRequestBody Body;
        
        public AddStaffRequest() {
        }
        
        public AddStaffRequest(FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddStaffRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddStaffRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FelicitySecurity.Core.FelicitySecurityDataServiceReference.Staff_dto item;
        
        public AddStaffRequestBody() {
        }
        
        public AddStaffRequestBody(FelicitySecurity.Core.FelicitySecurityDataServiceReference.Staff_dto item) {
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddStaffResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddStaffResponse", Namespace="http://tempuri.org/", Order=0)]
        public FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddStaffResponseBody Body;
        
        public AddStaffResponse() {
        }
        
        public AddStaffResponse(FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddStaffResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddStaffResponseBody {
        
        public AddStaffResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindAllStaffRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindAllStaff", Namespace="http://tempuri.org/", Order=0)]
        public FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllStaffRequestBody Body;
        
        public FindAllStaffRequest() {
        }
        
        public FindAllStaffRequest(FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllStaffRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class FindAllStaffRequestBody {
        
        public FindAllStaffRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindAllStaffResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindAllStaffResponse", Namespace="http://tempuri.org/", Order=0)]
        public FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllStaffResponseBody Body;
        
        public FindAllStaffResponse() {
        }
        
        public FindAllStaffResponse(FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllStaffResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindAllStaffResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FelicitySecurity.Core.FelicitySecurityDataServiceReference.Staff_dto[] FindAllStaffResult;
        
        public FindAllStaffResponseBody() {
        }
        
        public FindAllStaffResponseBody(FelicitySecurity.Core.FelicitySecurityDataServiceReference.Staff_dto[] FindAllStaffResult) {
            this.FindAllStaffResult = FindAllStaffResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateAdministratorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateAdministrator", Namespace="http://tempuri.org/", Order=0)]
        public FelicitySecurity.Core.FelicitySecurityDataServiceReference.UpdateAdministratorRequestBody Body;
        
        public UpdateAdministratorRequest() {
        }
        
        public UpdateAdministratorRequest(FelicitySecurity.Core.FelicitySecurityDataServiceReference.UpdateAdministratorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateAdministratorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FelicitySecurity.Core.FelicitySecurityDataServiceReference.Administrators_dto item;
        
        public UpdateAdministratorRequestBody() {
        }
        
        public UpdateAdministratorRequestBody(FelicitySecurity.Core.FelicitySecurityDataServiceReference.Administrators_dto item) {
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateAdministratorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateAdministratorResponse", Namespace="http://tempuri.org/", Order=0)]
        public FelicitySecurity.Core.FelicitySecurityDataServiceReference.UpdateAdministratorResponseBody Body;
        
        public UpdateAdministratorResponse() {
        }
        
        public UpdateAdministratorResponse(FelicitySecurity.Core.FelicitySecurityDataServiceReference.UpdateAdministratorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateAdministratorResponseBody {
        
        public UpdateAdministratorResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FelicitySecurityDataServiceSoapChannel : FelicitySecurity.Core.FelicitySecurityDataServiceReference.FelicitySecurityDataServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FelicitySecurityDataServiceSoapClient : System.ServiceModel.ClientBase<FelicitySecurity.Core.FelicitySecurityDataServiceReference.FelicitySecurityDataServiceSoap>, FelicitySecurity.Core.FelicitySecurityDataServiceReference.FelicitySecurityDataServiceSoap {
        
        public FelicitySecurityDataServiceSoapClient() {
        }
        
        public FelicitySecurityDataServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FelicitySecurityDataServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FelicitySecurityDataServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FelicitySecurityDataServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddAdministratorResponse FelicitySecurity.Core.FelicitySecurityDataServiceReference.FelicitySecurityDataServiceSoap.AddAdministrator(FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddAdministratorRequest request) {
            return base.Channel.AddAdministrator(request);
        }
        
        public void AddAdministrator(FelicitySecurity.Core.FelicitySecurityDataServiceReference.Administrators_dto item) {
            FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddAdministratorRequest inValue = new FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddAdministratorRequest();
            inValue.Body = new FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddAdministratorRequestBody();
            inValue.Body.item = item;
            FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddAdministratorResponse retVal = ((FelicitySecurity.Core.FelicitySecurityDataServiceReference.FelicitySecurityDataServiceSoap)(this)).AddAdministrator(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddAdministratorResponse> FelicitySecurity.Core.FelicitySecurityDataServiceReference.FelicitySecurityDataServiceSoap.AddAdministratorAsync(FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddAdministratorRequest request) {
            return base.Channel.AddAdministratorAsync(request);
        }
        
        public System.Threading.Tasks.Task<FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddAdministratorResponse> AddAdministratorAsync(FelicitySecurity.Core.FelicitySecurityDataServiceReference.Administrators_dto item) {
            FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddAdministratorRequest inValue = new FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddAdministratorRequest();
            inValue.Body = new FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddAdministratorRequestBody();
            inValue.Body.item = item;
            return ((FelicitySecurity.Core.FelicitySecurityDataServiceReference.FelicitySecurityDataServiceSoap)(this)).AddAdministratorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllAdministratorsResponse FelicitySecurity.Core.FelicitySecurityDataServiceReference.FelicitySecurityDataServiceSoap.FindAllAdministrators(FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllAdministratorsRequest request) {
            return base.Channel.FindAllAdministrators(request);
        }
        
        public FelicitySecurity.Core.FelicitySecurityDataServiceReference.Administrators_dto[] FindAllAdministrators() {
            FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllAdministratorsRequest inValue = new FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllAdministratorsRequest();
            inValue.Body = new FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllAdministratorsRequestBody();
            FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllAdministratorsResponse retVal = ((FelicitySecurity.Core.FelicitySecurityDataServiceReference.FelicitySecurityDataServiceSoap)(this)).FindAllAdministrators(inValue);
            return retVal.Body.FindAllAdministratorsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllAdministratorsResponse> FelicitySecurity.Core.FelicitySecurityDataServiceReference.FelicitySecurityDataServiceSoap.FindAllAdministratorsAsync(FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllAdministratorsRequest request) {
            return base.Channel.FindAllAdministratorsAsync(request);
        }
        
        public System.Threading.Tasks.Task<FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllAdministratorsResponse> FindAllAdministratorsAsync() {
            FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllAdministratorsRequest inValue = new FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllAdministratorsRequest();
            inValue.Body = new FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllAdministratorsRequestBody();
            return ((FelicitySecurity.Core.FelicitySecurityDataServiceReference.FelicitySecurityDataServiceSoap)(this)).FindAllAdministratorsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddMemberResponse FelicitySecurity.Core.FelicitySecurityDataServiceReference.FelicitySecurityDataServiceSoap.AddMember(FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddMemberRequest request) {
            return base.Channel.AddMember(request);
        }
        
        public void AddMember(FelicitySecurity.Core.FelicitySecurityDataServiceReference.Members_dto item) {
            FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddMemberRequest inValue = new FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddMemberRequest();
            inValue.Body = new FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddMemberRequestBody();
            inValue.Body.item = item;
            FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddMemberResponse retVal = ((FelicitySecurity.Core.FelicitySecurityDataServiceReference.FelicitySecurityDataServiceSoap)(this)).AddMember(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddMemberResponse> FelicitySecurity.Core.FelicitySecurityDataServiceReference.FelicitySecurityDataServiceSoap.AddMemberAsync(FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddMemberRequest request) {
            return base.Channel.AddMemberAsync(request);
        }
        
        public System.Threading.Tasks.Task<FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddMemberResponse> AddMemberAsync(FelicitySecurity.Core.FelicitySecurityDataServiceReference.Members_dto item) {
            FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddMemberRequest inValue = new FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddMemberRequest();
            inValue.Body = new FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddMemberRequestBody();
            inValue.Body.item = item;
            return ((FelicitySecurity.Core.FelicitySecurityDataServiceReference.FelicitySecurityDataServiceSoap)(this)).AddMemberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllMembersResponse FelicitySecurity.Core.FelicitySecurityDataServiceReference.FelicitySecurityDataServiceSoap.FindAllMembers(FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllMembersRequest request) {
            return base.Channel.FindAllMembers(request);
        }
        
        public FelicitySecurity.Core.FelicitySecurityDataServiceReference.Members_dto[] FindAllMembers() {
            FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllMembersRequest inValue = new FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllMembersRequest();
            inValue.Body = new FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllMembersRequestBody();
            FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllMembersResponse retVal = ((FelicitySecurity.Core.FelicitySecurityDataServiceReference.FelicitySecurityDataServiceSoap)(this)).FindAllMembers(inValue);
            return retVal.Body.FindAllMembersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllMembersResponse> FelicitySecurity.Core.FelicitySecurityDataServiceReference.FelicitySecurityDataServiceSoap.FindAllMembersAsync(FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllMembersRequest request) {
            return base.Channel.FindAllMembersAsync(request);
        }
        
        public System.Threading.Tasks.Task<FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllMembersResponse> FindAllMembersAsync() {
            FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllMembersRequest inValue = new FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllMembersRequest();
            inValue.Body = new FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllMembersRequestBody();
            return ((FelicitySecurity.Core.FelicitySecurityDataServiceReference.FelicitySecurityDataServiceSoap)(this)).FindAllMembersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddStaffResponse FelicitySecurity.Core.FelicitySecurityDataServiceReference.FelicitySecurityDataServiceSoap.AddStaff(FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddStaffRequest request) {
            return base.Channel.AddStaff(request);
        }
        
        public void AddStaff(FelicitySecurity.Core.FelicitySecurityDataServiceReference.Staff_dto item) {
            FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddStaffRequest inValue = new FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddStaffRequest();
            inValue.Body = new FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddStaffRequestBody();
            inValue.Body.item = item;
            FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddStaffResponse retVal = ((FelicitySecurity.Core.FelicitySecurityDataServiceReference.FelicitySecurityDataServiceSoap)(this)).AddStaff(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddStaffResponse> FelicitySecurity.Core.FelicitySecurityDataServiceReference.FelicitySecurityDataServiceSoap.AddStaffAsync(FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddStaffRequest request) {
            return base.Channel.AddStaffAsync(request);
        }
        
        public System.Threading.Tasks.Task<FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddStaffResponse> AddStaffAsync(FelicitySecurity.Core.FelicitySecurityDataServiceReference.Staff_dto item) {
            FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddStaffRequest inValue = new FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddStaffRequest();
            inValue.Body = new FelicitySecurity.Core.FelicitySecurityDataServiceReference.AddStaffRequestBody();
            inValue.Body.item = item;
            return ((FelicitySecurity.Core.FelicitySecurityDataServiceReference.FelicitySecurityDataServiceSoap)(this)).AddStaffAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllStaffResponse FelicitySecurity.Core.FelicitySecurityDataServiceReference.FelicitySecurityDataServiceSoap.FindAllStaff(FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllStaffRequest request) {
            return base.Channel.FindAllStaff(request);
        }
        
        public FelicitySecurity.Core.FelicitySecurityDataServiceReference.Staff_dto[] FindAllStaff() {
            FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllStaffRequest inValue = new FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllStaffRequest();
            inValue.Body = new FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllStaffRequestBody();
            FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllStaffResponse retVal = ((FelicitySecurity.Core.FelicitySecurityDataServiceReference.FelicitySecurityDataServiceSoap)(this)).FindAllStaff(inValue);
            return retVal.Body.FindAllStaffResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllStaffResponse> FelicitySecurity.Core.FelicitySecurityDataServiceReference.FelicitySecurityDataServiceSoap.FindAllStaffAsync(FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllStaffRequest request) {
            return base.Channel.FindAllStaffAsync(request);
        }
        
        public System.Threading.Tasks.Task<FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllStaffResponse> FindAllStaffAsync() {
            FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllStaffRequest inValue = new FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllStaffRequest();
            inValue.Body = new FelicitySecurity.Core.FelicitySecurityDataServiceReference.FindAllStaffRequestBody();
            return ((FelicitySecurity.Core.FelicitySecurityDataServiceReference.FelicitySecurityDataServiceSoap)(this)).FindAllStaffAsync(inValue);
        }
        
        public void RemoveAdministrator(int administratorId) {
            base.Channel.RemoveAdministrator(administratorId);
        }
        
        public System.Threading.Tasks.Task RemoveAdministratorAsync(int administratorId) {
            return base.Channel.RemoveAdministratorAsync(administratorId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FelicitySecurity.Core.FelicitySecurityDataServiceReference.UpdateAdministratorResponse FelicitySecurity.Core.FelicitySecurityDataServiceReference.FelicitySecurityDataServiceSoap.UpdateAdministrator(FelicitySecurity.Core.FelicitySecurityDataServiceReference.UpdateAdministratorRequest request) {
            return base.Channel.UpdateAdministrator(request);
        }
        
        public void UpdateAdministrator(FelicitySecurity.Core.FelicitySecurityDataServiceReference.Administrators_dto item) {
            FelicitySecurity.Core.FelicitySecurityDataServiceReference.UpdateAdministratorRequest inValue = new FelicitySecurity.Core.FelicitySecurityDataServiceReference.UpdateAdministratorRequest();
            inValue.Body = new FelicitySecurity.Core.FelicitySecurityDataServiceReference.UpdateAdministratorRequestBody();
            inValue.Body.item = item;
            FelicitySecurity.Core.FelicitySecurityDataServiceReference.UpdateAdministratorResponse retVal = ((FelicitySecurity.Core.FelicitySecurityDataServiceReference.FelicitySecurityDataServiceSoap)(this)).UpdateAdministrator(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FelicitySecurity.Core.FelicitySecurityDataServiceReference.UpdateAdministratorResponse> FelicitySecurity.Core.FelicitySecurityDataServiceReference.FelicitySecurityDataServiceSoap.UpdateAdministratorAsync(FelicitySecurity.Core.FelicitySecurityDataServiceReference.UpdateAdministratorRequest request) {
            return base.Channel.UpdateAdministratorAsync(request);
        }
        
        public System.Threading.Tasks.Task<FelicitySecurity.Core.FelicitySecurityDataServiceReference.UpdateAdministratorResponse> UpdateAdministratorAsync(FelicitySecurity.Core.FelicitySecurityDataServiceReference.Administrators_dto item) {
            FelicitySecurity.Core.FelicitySecurityDataServiceReference.UpdateAdministratorRequest inValue = new FelicitySecurity.Core.FelicitySecurityDataServiceReference.UpdateAdministratorRequest();
            inValue.Body = new FelicitySecurity.Core.FelicitySecurityDataServiceReference.UpdateAdministratorRequestBody();
            inValue.Body.item = item;
            return ((FelicitySecurity.Core.FelicitySecurityDataServiceReference.FelicitySecurityDataServiceSoap)(this)).UpdateAdministratorAsync(inValue);
        }
    }
}
