//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FelicitySecurity.Core.Data.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FelicityLiveEntities : DbContext
    {
        public FelicityLiveEntities()
            : base("name=FelicityLiveEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminTable> AdminTable { get; set; }
        public virtual DbSet<FacesTable> FacesTable { get; set; }
        public virtual DbSet<MemberTable> MemberTable { get; set; }
        public virtual DbSet<StaffTable> StaffTable { get; set; }
    }
}
